apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: iad.ocir.io/idozijgcstuv/repo/api:latest 
          ports:
            - containerPort: 8080
          env:
            - name: REGION
              value: "region-a"
            - name: WORKER_URL
              value: "http://207.211.190.124"
