apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: iad.ocir.io/idozijgcstuv/repo/frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: REGION
              value: "region-a"
            - name: API_URL
              value: "http://api:8080"
          
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi" 
